### PR TITLE
Local storage to master merge request

### PR DESCRIPTION
**Pull request by glitcher255**
Form now stores user information locally and fills it automatically

### CODE REVIEW

**Comment by huseyinbiyik** [comment]
Hi @glitcher255,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

Alt Text

## Invalid Code Review Request

- You have submitted a project, that has no contribution from your pair programming partner. Kindly check the project requirements [here](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/10_localstorage.md#work-and-submission-mode).
- Please make sure you have set up linters for Eslint.
-  Please make sure your commit messages are meaningful and descriptive for your next commits. Use imperative tense and capitalize the first word. For example, "Add logo to navigation bar"


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by glitcher255** [comment]
@huseyinbiyik My partner was on call with me the whole time during the creation of this project, besides, its now complete, what would you like him to add now? will an empty space suffice- 

You have not explained what eslint is, its not something I have come across before, no reviewer before you ever mentioned eslint- you need to elaborate here, or maybe send a link to explain what you're talking about

The commits are already capitalized - You need to elaborate on what the requirment here is

**Comment by huseyinbiyik** [comment]
Hello @glitcher255 and @DavidCazco36,

- Regarding pair programming contribution, now you both have committed, so no problem. But please make sure you both commit to your next pair programming project before submit for your first review. Since we don't check your Zoom call, that's the only way to prove that you are doing pair programming. 👍
- Regarding linters, you should have come across the first pair programming project of the week. Kindly check the [link](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/7_mobile_menu.md#:~:text=For%20this%20project%2C%20you%20should%20add%20the%20JavaScript%20%2B%20HTML%20%2B%20CSS%20linter.) and set up your linters according to the instructions. Sorry if the previous Code Reviewer didn't bring this to your notice. I will warn them. 📝
- Please make sure your commit messages are meaningful and descriptive for your next commits. Use imperative tense and capitalize the first word. For example, instead of 'Added local storage', 'Add LocalStorage function to save form inputs' is better. Because it is descriptive and imperative 👍

**Comment by glitcher255** [comment]
@huseyinbiyik Me and david are getting a few obnoxious linter errors that are not auto fixed by npx eslint . --fix 

1- such as - Camel case requirments - we did those
2- Use array destructuring - Extremely painful to adjust entire code for to sort them out, is this really mandatory? also broke my code.. again
3- 'closeButton' is defined but never used - CloseButton is defined and used from the html.index file, but apparently the linters can not recognize this, as far as I can tell this is unfixable- 
4- Unary operator '++' used - yet another unfixable linter error that completely breaks code functionality beyond repair

Do we need to adjust through all of these linters? if yes, then this is is taking a lot longer than the entire project took to develope, worse still, we don't know how to fix them or they are unfixable - this is a painful experience to say the least.

**Comment by huseyinbiyik** [comment]
Hello again. I checked your repo and the errors and unfortunately, you should fix all those linter issues.

**Review by mahbubul14 — APPROVED** [review]
# Project Approved :trophy: :tada: 

**Hi @Team,** 

Your project is complete!  You have done it exceptionally well. it's time to merge it :100: 
Congratulations! 🎉 

### To Highlight :+1: 

:heavy_check_mark: No linter error.
:heavy_check_mark: Descriptive readme file.
:heavy_check_mark: Well-implemented requirements.

### Optional suggestions :arrow_down_small: 

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.

- [ ] The commit message should be written in the imperative tense and the first letter should also be capitalized. `Ex: "Fix bug" instead of "Bug fixed".` [For more details...](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also connect with me on [slack](https://microverse-students.slack.com/team/U01J39GL614)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Pull request merged**
